version: 2
# The following stanza defines a map named defaults with a variable that may be
# inserted using the YAML merge (<<: *) key later in the file to save some
# typing. See http://yaml.org/type/merge.html for details.
defaults: &defaults
  docker:
    - image: circleci/node:12.10.0

jobs:
  main:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: ./.circleci/main.sh

workflows:
  version: 2
  main:
    jobs:
      - main:
          context: reaction-build-read
