version: 2
jobs:
  dockerfile-lint:
    docker:
      - image: hadolint/hadolint:v1.6.6-6-g254b4ff
    steps:
      - checkout
      - run:
          name: Lint node-dev/10.16.3-v1 dockerfile
          command: hadolint ./images/node-dev/10-16-3-v1/Dockerfile
      - run:
          name: Lint node-dev/12.10.0-v1 dockerfile
          command: hadolint ./images/node-dev/12-10-0-v1/Dockerfile
      - run:
          name: Lint node-prod/10.16.3-v1 dockerfile
          command: hadolint ./images/node-prod/10-16-3-v1/Dockerfile
      - run:
          name: Lint node-prod/12.10.0-v1 dockerfile
          command: hadolint ./images/node-prod/12-10-0-v1/Dockerfile

  docker-build:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run:
          name: Docker build node-dev/10.16.3-v1
          command: ./images/node-dev/10-16-3-v1/build.sh
      - run:
          name: Docker build node-dev/12.10.0-v1
          command: ./images/node-dev/12-10-0-v1/build.sh
      - run:
          name: Docker build node-prod/10.16.3-v1
          command: ./images/node-prod/10-16-3-v1/build.sh
      - run:
          name: Docker build node-prod/12.10.0-v1
          command: ./images/node-prod/12-10-0-v1/build.sh

  docker-push:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run:
          name: Docker Push
          command: |
            if [ -z "$CIRCLE_PR_USERNAME" ]; then \
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
              ./images/node-dev/10-16-3-v1/push.sh
              ./images/node-dev/12-10-0-v1/push.sh
              ./images/node-prod/10-16-3-v1/push.sh
              ./images/node-prod/12-10-0-v1/push.sh
            else
              echo "No deploy for forks"
            fi

workflows:
  version: 2
  check_and_deploy:
    jobs:
      - dockerfile-lint
      - docker-build:
          context: reaction-build-read
          requires:
            - dockerfile-lint
      - docker-push:
          context: reaction-publish-docker
          requires:
            - docker-build
          filters:
            branches:
              only: trunk